-- Research-project collaboration: membership, scoped saved data, invitations,
-- join requests, immutable activity summaries, and project-aware RLS.

-- ─── Public user directory (email remains visible only to shared projects) ──

CREATE TABLE IF NOT EXISTS user_profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        TEXT NOT NULL,
  display_name TEXT NOT NULL DEFAULT '',
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_email
  ON user_profiles (lower(email));

CREATE OR REPLACE FUNCTION sync_user_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RETURN NEW;
  END IF;
  INSERT INTO public.user_profiles (id, email, display_name, updated_at)
  VALUES (
    NEW.id,
    lower(trim(NEW.email)),
    coalesce(NEW.raw_user_meta_data ->> 'display_name', ''),
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_user_profile_from_auth ON auth.users;
CREATE TRIGGER sync_user_profile_from_auth
  AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
  FOR EACH ROW EXECUTE FUNCTION sync_user_profile();

INSERT INTO user_profiles (id, email, display_name)
SELECT id, lower(trim(email)), coalesce(raw_user_meta_data ->> 'display_name', '')
FROM auth.users
WHERE email IS NOT NULL
ON CONFLICT (id) DO UPDATE SET
  email = excluded.email,
  display_name = excluded.display_name,
  updated_at = now();

-- ─── Projects and membership ──────────────────────────────────────────────

CREATE TABLE research_projects (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code        TEXT NOT NULL UNIQUE CHECK (code ~ '^[0-9]{4}$'),
  name        TEXT NOT NULL CHECK (char_length(trim(name)) BETWEEN 1 AND 120),
  description TEXT NOT NULL DEFAULT '' CHECK (char_length(description) <= 1000),
  owner_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE research_project_members (
  project_id UUID NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id)
);

CREATE UNIQUE INDEX idx_research_project_single_owner
  ON research_project_members(project_id) WHERE role = 'owner';
CREATE INDEX idx_research_project_members_user
  ON research_project_members(user_id, project_id);

CREATE TABLE research_project_invitations (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id    UUID NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  invitee_email TEXT NOT NULL,
  inviter_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'accepted', 'declined', 'revoked')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at  TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_research_project_pending_invite
  ON research_project_invitations(project_id, lower(invitee_email))
  WHERE status = 'pending';

CREATE TABLE research_project_join_requests (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   UUID NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  requester_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status       TEXT NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at   TIMESTAMPTZ,
  decided_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_research_project_pending_request
  ON research_project_join_requests(project_id, requester_id)
  WHERE status = 'pending';

CREATE TABLE project_activity (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id           UUID NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  category             TEXT NOT NULL CHECK (category IN ('data', 'member')),
  action               TEXT NOT NULL,
  actor_id             UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_email          TEXT NOT NULL DEFAULT '',
  actor_display_name   TEXT NOT NULL DEFAULT '',
  entity_type          TEXT NOT NULL,
  entity_id            TEXT,
  entity_name          TEXT NOT NULL DEFAULT '',
  summary              TEXT NOT NULL,
  occurrence_count     INTEGER NOT NULL DEFAULT 1,
  revision_from        BIGINT,
  revision_to          BIGINT,
  first_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_project_activity_feed
  ON project_activity(project_id, last_at DESC, id DESC);

-- ─── Authorization helpers ────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION current_user_email()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT lower(coalesce((SELECT email FROM auth.users WHERE id = auth.uid()), ''));
$$;

CREATE OR REPLACE FUNCTION project_role(p_project_id UUID)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role
  FROM research_project_members
  WHERE project_id = p_project_id AND user_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION is_project_member(p_project_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM research_project_members
    WHERE project_id = p_project_id AND user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION can_edit_project(p_project_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM research_project_members m
    JOIN research_projects p ON p.id = m.project_id
    WHERE m.project_id = p_project_id
      AND m.user_id = auth.uid()
      AND m.role IN ('owner', 'admin')
      AND p.status = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION shares_project_with(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p_user_id = auth.uid() OR EXISTS (
    SELECT 1
    FROM research_project_members mine
    JOIN research_project_members theirs
      ON theirs.project_id = mine.project_id
    WHERE mine.user_id = auth.uid() AND theirs.user_id = p_user_id
  );
$$;

CREATE OR REPLACE FUNCTION can_view_user_profile(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT shares_project_with(p_user_id) OR EXISTS (
    SELECT 1
    FROM research_project_join_requests r
    JOIN research_project_members manager ON manager.project_id = r.project_id
    WHERE r.requester_id = p_user_id AND r.status = 'pending'
      AND manager.user_id = auth.uid() AND manager.role IN ('owner', 'admin')
  );
$$;

-- ─── RLS for project tables ───────────────────────────────────────────────

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_project_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_project_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_activity ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles visible to self and project peers"
  ON user_profiles FOR SELECT
  USING (can_view_user_profile(id));

CREATE POLICY "Projects visible to members and pending participants"
  ON research_projects FOR SELECT
  USING (
    is_project_member(id)
    OR EXISTS (
      SELECT 1 FROM research_project_invitations i
      WHERE i.project_id = id AND i.status = 'pending'
        AND lower(i.invitee_email) = current_user_email()
    )
    OR EXISTS (
      SELECT 1 FROM research_project_join_requests r
      WHERE r.project_id = id AND r.requester_id = auth.uid()
    )
  );

CREATE POLICY "Members visible inside project"
  ON research_project_members FOR SELECT
  USING (is_project_member(project_id));

CREATE POLICY "Invitations visible to managers and invitee"
  ON research_project_invitations FOR SELECT
  USING (
    project_role(project_id) IN ('owner', 'admin')
    OR lower(invitee_email) = current_user_email()
  );

CREATE POLICY "Join requests visible to managers and requester"
  ON research_project_join_requests FOR SELECT
  USING (
    project_role(project_id) IN ('owner', 'admin')
    OR requester_id = auth.uid()
  );

CREATE POLICY "Activity visible to project members"
  ON project_activity FOR SELECT
  USING (is_project_member(project_id));

-- ─── Project activity writer; callable only by triggers/RPC functions ─────

CREATE OR REPLACE FUNCTION record_project_activity(
  p_project_id UUID,
  p_category TEXT,
  p_action TEXT,
  p_entity_type TEXT,
  p_entity_id TEXT,
  p_entity_name TEXT,
  p_summary TEXT,
  p_revision_from BIGINT DEFAULT NULL,
  p_revision_to BIGINT DEFAULT NULL,
  p_coalesce BOOLEAN DEFAULT FALSE
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_actor_id UUID := auth.uid();
  v_email TEXT := '';
  v_name TEXT := '';
  v_recent_id BIGINT;
BEGIN
  SELECT lower(coalesce(u.email, '')),
         coalesce(u.raw_user_meta_data ->> 'display_name', '')
  INTO v_email, v_name
  FROM auth.users u WHERE u.id = v_actor_id;

  IF p_coalesce THEN
    SELECT id INTO v_recent_id
    FROM project_activity
    WHERE project_id = p_project_id
      AND actor_id IS NOT DISTINCT FROM v_actor_id
      AND action = p_action
      AND entity_type = p_entity_type
      AND entity_id IS NOT DISTINCT FROM p_entity_id
      AND last_at >= now() - interval '5 minutes'
    ORDER BY last_at DESC, id DESC
    LIMIT 1
    FOR UPDATE;
  END IF;

  IF v_recent_id IS NOT NULL THEN
    UPDATE project_activity SET
      actor_email = v_email,
      actor_display_name = v_name,
      summary = p_summary,
      entity_name = p_entity_name,
      occurrence_count = occurrence_count + 1,
      revision_to = coalesce(p_revision_to, revision_to),
      last_at = now()
    WHERE id = v_recent_id;
  ELSE
    INSERT INTO project_activity (
      project_id, category, action, actor_id, actor_email, actor_display_name,
      entity_type, entity_id, entity_name, summary,
      revision_from, revision_to
    ) VALUES (
      p_project_id, p_category, p_action, v_actor_id, v_email, v_name,
      p_entity_type, p_entity_id, p_entity_name, p_summary,
      p_revision_from, p_revision_to
    );
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION record_project_activity(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, BIGINT, BOOLEAN) FROM PUBLIC;

-- ─── Project RPCs ─────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION create_research_project(p_name TEXT, p_description TEXT DEFAULT '')
RETURNS research_projects
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_project research_projects;
  v_code TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF char_length(trim(p_name)) NOT BETWEEN 1 AND 120 THEN
    RAISE EXCEPTION 'Project name is required';
  END IF;
  LOOP
    v_code := lpad(floor(random() * 10000)::integer::text, 4, '0');
    BEGIN
      INSERT INTO research_projects (code, name, description, owner_id)
      VALUES (v_code, trim(p_name), left(coalesce(p_description, ''), 1000), auth.uid())
      RETURNING * INTO v_project;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      -- Four digits are intentionally easy to share; retry on collision.
    END;
  END LOOP;

  INSERT INTO research_project_members(project_id, user_id, role)
  VALUES (v_project.id, auth.uid(), 'owner');
  PERFORM record_project_activity(v_project.id, 'member', 'project_created',
    'project', v_project.id::text, v_project.name,
    '创建了课题「' || v_project.name || '」');
  RETURN v_project;
END;
$$;

CREATE OR REPLACE FUNCTION lookup_research_project(p_code TEXT)
RETURNS TABLE(project_id UUID, code TEXT, name TEXT, owner_name TEXT)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.code, p.name,
         coalesce(up.display_name, split_part(up.email, '@', 1), '负责人')
  FROM research_projects p
  LEFT JOIN user_profiles up ON up.id = p.owner_id
  WHERE p.code = upper(trim(p_code)) AND p.status = 'active';
$$;

CREATE OR REPLACE FUNCTION invite_research_project_member(p_project_id UUID, p_email TEXT)
RETURNS research_project_invitations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite research_project_invitations;
  v_email TEXT := lower(trim(p_email));
  v_existing UUID;
BEGIN
  IF project_role(p_project_id) NOT IN ('owner', 'admin') OR NOT can_edit_project(p_project_id) THEN
    RAISE EXCEPTION 'Not allowed';
  END IF;
  IF v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' THEN
    RAISE EXCEPTION 'Invalid email';
  END IF;
  SELECT id INTO v_existing FROM user_profiles WHERE lower(email) = v_email;
  IF v_existing IS NOT NULL AND EXISTS (
    SELECT 1 FROM research_project_members
    WHERE project_id = p_project_id AND user_id = v_existing
  ) THEN
    RAISE EXCEPTION 'Already a member';
  END IF;
  IF EXISTS (
    SELECT 1 FROM research_project_invitations
    WHERE project_id = p_project_id AND lower(invitee_email) = v_email AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'Invitation already pending';
  END IF;
  INSERT INTO research_project_invitations(project_id, invitee_email, inviter_id)
  VALUES (p_project_id, v_email, auth.uid()) RETURNING * INTO v_invite;
  PERFORM record_project_activity(p_project_id, 'member', 'member_invited',
    'invitation', v_invite.id::text, v_email, '邀请了 ' || v_email);
  RETURN v_invite;
END;
$$;

CREATE OR REPLACE FUNCTION respond_research_project_invitation(p_invitation_id UUID, p_accept BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite research_project_invitations;
BEGIN
  SELECT * INTO v_invite FROM research_project_invitations
  WHERE id = p_invitation_id AND status = 'pending' FOR UPDATE;
  IF NOT FOUND OR lower(v_invite.invitee_email) <> current_user_email() THEN
    RAISE EXCEPTION 'Invitation not found';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM research_projects WHERE id = v_invite.project_id AND status = 'active') THEN
    RAISE EXCEPTION 'Project is archived';
  END IF;
  IF p_accept THEN
    INSERT INTO research_project_members(project_id, user_id, role)
    VALUES (v_invite.project_id, auth.uid(), 'member')
    ON CONFLICT (project_id, user_id) DO NOTHING;
    UPDATE research_project_invitations
      SET status = 'accepted', responded_at = now() WHERE id = p_invitation_id;
    PERFORM record_project_activity(v_invite.project_id, 'member', 'invitation_accepted',
      'member', auth.uid()::text, current_user_email(), '接受邀请并加入了课题');
  ELSE
    UPDATE research_project_invitations
      SET status = 'declined', responded_at = now() WHERE id = p_invitation_id;
    PERFORM record_project_activity(v_invite.project_id, 'member', 'invitation_declined',
      'invitation', v_invite.id::text, v_invite.invitee_email, '拒绝了课题邀请');
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION request_research_project_join(p_code TEXT)
RETURNS research_project_join_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_project_id UUID;
  v_request research_project_join_requests;
BEGIN
  SELECT id INTO v_project_id FROM research_projects
  WHERE code = upper(trim(p_code)) AND status = 'active';
  IF v_project_id IS NULL THEN RAISE EXCEPTION 'Project not found'; END IF;
  IF is_project_member(v_project_id) THEN RAISE EXCEPTION 'Already a member'; END IF;
  IF EXISTS (SELECT 1 FROM research_project_join_requests
             WHERE project_id = v_project_id AND requester_id = auth.uid() AND status = 'pending') THEN
    RAISE EXCEPTION 'Request already pending';
  END IF;
  INSERT INTO research_project_join_requests(project_id, requester_id)
  VALUES (v_project_id, auth.uid()) RETURNING * INTO v_request;
  PERFORM record_project_activity(v_project_id, 'member', 'join_requested',
    'join_request', v_request.id::text, current_user_email(), '申请加入课题');
  RETURN v_request;
END;
$$;

CREATE OR REPLACE FUNCTION review_research_project_join_request(p_request_id UUID, p_approve BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request research_project_join_requests;
BEGIN
  SELECT * INTO v_request FROM research_project_join_requests
  WHERE id = p_request_id AND status = 'pending' FOR UPDATE;
  IF NOT FOUND OR project_role(v_request.project_id) NOT IN ('owner', 'admin')
     OR NOT can_edit_project(v_request.project_id) THEN
    RAISE EXCEPTION 'Not allowed';
  END IF;
  UPDATE research_project_join_requests SET
    status = CASE WHEN p_approve THEN 'approved' ELSE 'rejected' END,
    decided_at = now(), decided_by = auth.uid()
  WHERE id = p_request_id;
  IF p_approve THEN
    INSERT INTO research_project_members(project_id, user_id, role)
    VALUES (v_request.project_id, v_request.requester_id, 'member')
    ON CONFLICT (project_id, user_id) DO NOTHING;
  END IF;
  PERFORM record_project_activity(v_request.project_id, 'member',
    CASE WHEN p_approve THEN 'join_approved' ELSE 'join_rejected' END,
    'join_request', v_request.id::text, '',
    CASE WHEN p_approve THEN '批准了一项加入申请' ELSE '拒绝了一项加入申请' END);
END;
$$;

CREATE OR REPLACE FUNCTION set_research_project_member_role(
  p_project_id UUID, p_user_id UUID, p_role TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_email TEXT;
BEGIN
  IF project_role(p_project_id) <> 'owner' OR NOT can_edit_project(p_project_id)
     OR p_role NOT IN ('admin', 'member') THEN
    RAISE EXCEPTION 'Only the owner can change administrator roles';
  END IF;
  IF p_user_id = auth.uid() OR NOT EXISTS (
    SELECT 1 FROM research_project_members
    WHERE project_id = p_project_id AND user_id = p_user_id AND role <> 'owner'
  ) THEN RAISE EXCEPTION 'Member not found'; END IF;
  UPDATE research_project_members SET role = p_role
  WHERE project_id = p_project_id AND user_id = p_user_id;
  SELECT email INTO v_email FROM user_profiles WHERE id = p_user_id;
  PERFORM record_project_activity(p_project_id, 'member', 'role_changed',
    'member', p_user_id::text, coalesce(v_email, ''),
    '将 ' || coalesce(v_email, '成员') || ' 的权限调整为' ||
    CASE WHEN p_role = 'admin' THEN '管理员' ELSE '成员' END);
END;
$$;

CREATE OR REPLACE FUNCTION remove_research_project_member(p_project_id UUID, p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_actor_role TEXT; v_target_role TEXT; v_email TEXT;
BEGIN
  v_actor_role := project_role(p_project_id);
  IF NOT can_edit_project(p_project_id) THEN RAISE EXCEPTION 'Project is read-only'; END IF;
  SELECT role INTO v_target_role FROM research_project_members
  WHERE project_id = p_project_id AND user_id = p_user_id;
  IF v_target_role IS NULL OR v_target_role = 'owner' THEN RAISE EXCEPTION 'Member not removable'; END IF;
  IF v_actor_role = 'owner' OR (v_actor_role = 'admin' AND v_target_role = 'member') THEN
    DELETE FROM research_project_members WHERE project_id = p_project_id AND user_id = p_user_id;
    SELECT email INTO v_email FROM user_profiles WHERE id = p_user_id;
    PERFORM record_project_activity(p_project_id, 'member', 'member_removed',
      'member', p_user_id::text, coalesce(v_email, ''),
      '移除了成员 ' || coalesce(v_email, ''));
  ELSE
    RAISE EXCEPTION 'Not allowed';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION leave_research_project(p_project_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_role TEXT;
BEGIN
  v_role := project_role(p_project_id);
  IF v_role IS NULL OR v_role = 'owner' THEN RAISE EXCEPTION 'Owner cannot leave'; END IF;
  PERFORM record_project_activity(p_project_id, 'member', 'member_left',
    'member', auth.uid()::text, current_user_email(), '离开了课题');
  DELETE FROM research_project_members WHERE project_id = p_project_id AND user_id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION set_research_project_archived(p_project_id UUID, p_archived BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_name TEXT;
BEGIN
  IF project_role(p_project_id) <> 'owner' THEN RAISE EXCEPTION 'Only owner can archive'; END IF;
  UPDATE research_projects SET status = CASE WHEN p_archived THEN 'archived' ELSE 'active' END,
    updated_at = now() WHERE id = p_project_id RETURNING name INTO v_name;
  PERFORM record_project_activity(p_project_id, 'member',
    CASE WHEN p_archived THEN 'project_archived' ELSE 'project_restored' END,
    'project', p_project_id::text, v_name,
    CASE WHEN p_archived THEN '归档了课题' ELSE '恢复了课题' END);
END;
$$;

-- ─── Scope lnp_saved_items to personal or project data ────────────────────

ALTER TABLE lnp_saved_items
  ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES research_projects(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS last_modified_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_lnp_saved_items_project_type
  ON lnp_saved_items(project_id, type, created_at DESC);

DROP POLICY IF EXISTS "Users can read own items" ON lnp_saved_items;
DROP POLICY IF EXISTS "Users can create own items" ON lnp_saved_items;
DROP POLICY IF EXISTS "Users can update own items" ON lnp_saved_items;
DROP POLICY IF EXISTS "Users can delete own items" ON lnp_saved_items;

CREATE POLICY "Read personal or project items"
  ON lnp_saved_items FOR SELECT
  USING (
    (project_id IS NULL AND user_id = auth.uid())
    OR (project_id IS NOT NULL AND is_project_member(project_id))
  );

CREATE POLICY "Create personal or editable project items"
  ON lnp_saved_items FOR INSERT
  WITH CHECK (
    user_id = auth.uid() AND (
      project_id IS NULL OR can_edit_project(project_id)
    )
  );

CREATE POLICY "Update personal or editable project items"
  ON lnp_saved_items FOR UPDATE
  USING (
    (project_id IS NULL AND user_id = auth.uid())
    OR (project_id IS NOT NULL AND can_edit_project(project_id))
  )
  WITH CHECK (
    (project_id IS NULL AND user_id = auth.uid())
    OR (project_id IS NOT NULL AND can_edit_project(project_id))
  );

CREATE POLICY "Delete personal or editable project items"
  ON lnp_saved_items FOR DELETE
  USING (
    (project_id IS NULL AND user_id = auth.uid())
    OR (project_id IS NOT NULL AND can_edit_project(project_id))
  );

CREATE OR REPLACE FUNCTION protect_lnp_saved_item_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE v_parent lnp_saved_items;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.user_id IS DISTINCT FROM OLD.user_id OR NEW.project_id IS DISTINCT FROM OLD.project_id THEN
      RAISE EXCEPTION 'Saved item scope is immutable; copy it instead';
    END IF;
  END IF;
  IF NEW.parent_id IS NOT NULL THEN
    SELECT * INTO v_parent FROM lnp_saved_items WHERE id = NEW.parent_id;
    IF NOT FOUND OR NOT v_parent.is_folder OR v_parent.type <> NEW.type
       OR v_parent.project_id IS DISTINCT FROM NEW.project_id THEN
      RAISE EXCEPTION 'Parent folder must belong to the same scope and type';
    END IF;
  END IF;
  NEW.last_modified_by := auth.uid();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_lnp_saved_item_scope_trigger ON lnp_saved_items;
CREATE TRIGGER protect_lnp_saved_item_scope_trigger
  BEFORE INSERT OR UPDATE ON lnp_saved_items
  FOR EACH ROW EXECUTE FUNCTION protect_lnp_saved_item_scope();

CREATE OR REPLACE FUNCTION set_lnp_saved_item_sync_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  IF NEW.data IS DISTINCT FROM OLD.data THEN
    NEW.data_revision := OLD.data_revision + 1;
  ELSE
    NEW.data_revision := OLD.data_revision;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION audit_project_saved_item()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_project UUID; v_label TEXT; v_row lnp_saved_items;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_row := OLD;
  ELSE
    v_row := NEW;
  END IF;
  v_project := v_row.project_id;
  IF v_project IS NULL THEN RETURN v_row; END IF;
  v_label := CASE v_row.type
    WHEN 'formula' THEN '配方'
    WHEN 'preparation' THEN '制备参数'
    WHEN 'screening_session' THEN '配方筛选'
    WHEN 'ribogreen_result' THEN 'RiboGreen结果'
    WHEN 'tlnp_experiment' THEN 'tLNP批次'
    ELSE v_row.type END;

  IF TG_OP = 'INSERT' THEN
    PERFORM record_project_activity(v_project, 'data', 'created', v_row.type,
      v_row.id::text, v_row.name, '创建了' || v_label || '「' || v_row.name || '」',
      v_row.data_revision, v_row.data_revision, FALSE);
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM record_project_activity(v_project, 'data', 'deleted', v_row.type,
      v_row.id::text, v_row.name, '删除了' || v_label || '「' || v_row.name || '」');
  ELSE
    IF NEW.data IS DISTINCT FROM OLD.data THEN
      PERFORM record_project_activity(v_project, 'data', 'updated', v_row.type,
        v_row.id::text, v_row.name, '更新了' || v_label || '「' || v_row.name || '」',
        OLD.data_revision, NEW.data_revision, TRUE);
    END IF;
    IF NEW.name IS DISTINCT FROM OLD.name THEN
      PERFORM record_project_activity(v_project, 'data', 'renamed', v_row.type,
        v_row.id::text, v_row.name, '将「' || OLD.name || '」重命名为「' || NEW.name || '」');
    END IF;
    IF NEW.parent_id IS DISTINCT FROM OLD.parent_id THEN
      PERFORM record_project_activity(v_project, 'data', 'moved', v_row.type,
        v_row.id::text, v_row.name, '移动了' || v_label || '「' || v_row.name || '」');
    END IF;
  END IF;
  RETURN v_row;
END;
$$;

DROP TRIGGER IF EXISTS audit_project_saved_item_trigger ON lnp_saved_items;
CREATE TRIGGER audit_project_saved_item_trigger
  AFTER INSERT OR UPDATE OR DELETE ON lnp_saved_items
  FOR EACH ROW EXECUTE FUNCTION audit_project_saved_item();

-- Transactional insert of an application-prepared, ID-remapped collaboration bundle.
CREATE OR REPLACE FUNCTION copy_saved_item_bundle_to_project(p_project_id UUID, p_items JSONB)
RETURNS SETOF lnp_saved_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v JSONB; v_source lnp_saved_items; v_created lnp_saved_items; v_type TEXT;
        v_count INTEGER := 0;
BEGIN
  IF NOT can_edit_project(p_project_id) THEN RAISE EXCEPTION 'Not allowed'; END IF;
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Copy bundle is empty';
  END IF;
  FOR v IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_type := v ->> 'type';
    IF v_type NOT IN ('formula', 'preparation', 'screening_session', 'ribogreen_result', 'tlnp_experiment') THEN
      RAISE EXCEPTION 'Unsupported shared item type';
    END IF;
    SELECT * INTO v_source FROM lnp_saved_items
    WHERE id = (v ->> 'source_id')::uuid
      AND user_id = auth.uid() AND project_id IS NULL AND type = v_type;
    IF NOT FOUND THEN RAISE EXCEPTION 'Source item is unavailable'; END IF;
    INSERT INTO lnp_saved_items (
      id, user_id, project_id, type, is_folder, parent_id, name, data, sort_order
    ) VALUES (
      (v ->> 'id')::uuid, auth.uid(), p_project_id, v_type, FALSE, NULL,
      coalesce(nullif(trim(v ->> 'name'), ''), v_source.name),
      v -> 'data', coalesce((v ->> 'sort_order')::integer, 0)
    ) RETURNING * INTO v_created;
    v_count := v_count + 1;
    RETURN NEXT v_created;
  END LOOP;
  PERFORM record_project_activity(p_project_id, 'data', 'bundle_copied',
    'copy_bundle', NULL, '', '复制了一组关联数据（' || v_count || ' 条记录）');
END;
$$;

CREATE OR REPLACE FUNCTION copy_saved_item_bundle_to_personal(p_items JSONB)
RETURNS SETOF lnp_saved_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v JSONB; v_source lnp_saved_items; v_created lnp_saved_items; v_type TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Copy bundle is empty';
  END IF;
  FOR v IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_type := v ->> 'type';
    IF v_type NOT IN ('formula', 'preparation', 'screening_session', 'ribogreen_result', 'tlnp_experiment') THEN
      RAISE EXCEPTION 'Unsupported shared item type';
    END IF;
    SELECT * INTO v_source FROM lnp_saved_items
    WHERE id = (v ->> 'source_id')::uuid AND type = v_type
      AND project_id IS NOT NULL AND is_project_member(project_id);
    IF NOT FOUND THEN RAISE EXCEPTION 'Source item is unavailable'; END IF;
    INSERT INTO lnp_saved_items (
      id, user_id, project_id, type, is_folder, parent_id, name, data, sort_order
    ) VALUES (
      (v ->> 'id')::uuid, auth.uid(), NULL, v_type, FALSE, NULL,
      coalesce(nullif(trim(v ->> 'name'), ''), v_source.name),
      v -> 'data', coalesce((v ->> 'sort_order')::integer, 0)
    ) RETURNING * INTO v_created;
    RETURN NEXT v_created;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION create_research_project(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION sync_user_profile() FROM PUBLIC;
REVOKE ALL ON FUNCTION current_user_email() FROM PUBLIC;
REVOKE ALL ON FUNCTION project_role(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION is_project_member(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION can_edit_project(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION shares_project_with(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION can_view_user_profile(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION protect_lnp_saved_item_scope() FROM PUBLIC;
REVOKE ALL ON FUNCTION audit_project_saved_item() FROM PUBLIC;
REVOKE ALL ON FUNCTION lookup_research_project(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION invite_research_project_member(UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION respond_research_project_invitation(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION request_research_project_join(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION review_research_project_join_request(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION set_research_project_member_role(UUID, UUID, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION remove_research_project_member(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION leave_research_project(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION set_research_project_archived(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION copy_saved_item_bundle_to_project(UUID, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION copy_saved_item_bundle_to_personal(JSONB) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION create_research_project(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION current_user_email() TO authenticated;
GRANT EXECUTE ON FUNCTION project_role(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION is_project_member(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION can_edit_project(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION shares_project_with(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION can_view_user_profile(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION lookup_research_project(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION invite_research_project_member(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION respond_research_project_invitation(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION request_research_project_join(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION review_research_project_join_request(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION set_research_project_member_role(UUID, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION remove_research_project_member(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION leave_research_project(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION set_research_project_archived(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION copy_saved_item_bundle_to_project(UUID, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION copy_saved_item_bundle_to_personal(JSONB) TO authenticated;

REVOKE ALL ON TABLE user_profiles FROM anon, authenticated;
REVOKE ALL ON TABLE research_projects FROM anon, authenticated;
REVOKE ALL ON TABLE research_project_members FROM anon, authenticated;
REVOKE ALL ON TABLE research_project_invitations FROM anon, authenticated;
REVOKE ALL ON TABLE research_project_join_requests FROM anon, authenticated;
REVOKE ALL ON TABLE project_activity FROM anon, authenticated;

GRANT SELECT ON TABLE user_profiles TO authenticated;
GRANT SELECT ON TABLE research_projects TO authenticated;
GRANT SELECT ON TABLE research_project_members TO authenticated;
GRANT SELECT ON TABLE research_project_invitations TO authenticated;
GRANT SELECT ON TABLE research_project_join_requests TO authenticated;
GRANT SELECT ON TABLE project_activity TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'research_project_members'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE research_project_members;
  END IF;
END;
$$;
